FROM python:3.11-slim-bookworm

WORKDIR /workspace
COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY streamlit_app.py ./streamlit_app.py

EXPOSE 8501
ENV SERVE_HOST=model-serving
ENV SERVE_PORT=5000

CMD ["streamlit", "run", "streamlit_app.py", "--server.address=0.0.0.0", "--server.port=8501"]
