version: "3.9"
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    command: mlflow server --backend-store-uri /mlruns --default-artifact-root /mlruns --host 0.0.0.0 --port 5001
    volumes:
      - ./models/mlruns:/mlruns
    ports: ["5001:5001"]
